board/urls.py
from django.urls import path
from board.views import base_views, question_views, answer_views, vote_views, comment_views

app_name = 'board'  #네임 스페이스 설정

urlpatterns = [
    #127.0.0.1:8000/board/
    #메인페이지
    path('', base_views.index, name='index'),
    #질문목록
    path('boardlist/', base_views.boardlist, name='boardlist'),
    #질문/답변 상세
    path('<int:question_id>/', base_views.detail, name='detail'),
    #질문 등록
    path('question/create/', question_views.question_create, name='question_create'),
    #질문 수정일
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    #질문 삭제
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),
    #답변 등록
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    #답변 수정일
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    #답변 삭제
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),
    #질문 추천
    path('vote/question/<int:question_id>/', vote_views.vote_question, name='vote_question'),
    #질문 댓글 등록
    path('comment/create/question/<int:question_id>/', comment_views.comment_create_question, name='comment_create_question'),
    #질문 댓글 삭제
    path('comment/delete/question/<int:comment_id>/', comment_views.comment_delete_question, name='comment_delete_question'),
    #질문 댓글 수정
    path('comment/modify/question/<int:comment_id>/', comment_views.comment_modify_question, name='comment_modify_question'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from board.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', base_views.index),   #127.0.0.1:8000
    path('board/', include('board.urls')),
    path('common/', include('common.urls')),
    path('polls/', include('polls.urls')),
]

polls/urls.py
from django.urls import path
from polls import views
#네임 스페이스
app_name = 'poll'  #app_name변수에 poll앱 저장

urlpatterns = [
    path('', views.poll_list, name='index'), # 127.0.0.1:8000/poll/
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/vote/', views.vote, name='vote'),
]

polls/models.py
from django.db import models

# Question 모델(Model을 상속받음) - 테이블과 같은 의미
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField()

    def __str__(self):  #질문 내용이 문자로 출력됨
        return self.question_text

# Choice 모델
class Choice(models.Model):
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    question = models.ForeignKey(Question, on_delete=models.CASCADE) #외래키

    def __str__(self):
        return self.choice_text

polls/views.py
from django.shortcuts import render
from polls.models import Question


# 인덱스페이지
def poll_list(request):
    # db에 있는 모든 데이터 조회하기(select)
    question_list = Question.objects.all()
    return render(request, 'polls/poll_list.html', {'question_list': question_list})


# 상세페이지
def detail(request, pk):
    # 해당 id(순번)로 자료 조회(select)
    question = Question.objects.get(id=pk)
    return render(request, 'polls/detail.html', {'question': question})


# 투표하기
def vote(request, pk):
    question = Question.objects.get(id=pk)
    # 선택 자료 넘겨 받음
    try:
        choice_id = request.POST['choice']
        sel_choice = question.choice_set.get(id=choice_id)
    except:
        return render(request, 'polls/detail.html', {'question': question, 'error': '선택을 확인해 주세요.'})
    else:
        sel_choice.votes = sel_choice.votes + 1
        sel_choice.save()  # db에 저장
        return render(request, 'polls/vote_result.html', {'question': question})

templates/polls/detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <section>
        <h4 class="board-bottom py-2">투표하기</h4>
        <div class="card my-3">
            <h5 style="margin: 20px 100px 10px;">{{ question.question_text }}</h5>
            <form action="{% url 'poll:vote' question.id %}" method="post"
                style="width:500px; margin: 20px 120px;">
                {% csrf_token %}
                {% if error %}
                <div class="alert alert-danger"> * {{ error }}</div>
                {% endif %}
                {% for choice in question.choice_set.all %}
                <p style="font-size:1.2rem;">
                    <input type="radio" name="choice" id="choice" value="{{ choice.id }}">
                    <label for="choice">{{ choice.choice_text }}</label>
                </p>
                {% endfor %}
                <button type="submit" class="btn btn-success"> 투표 </button>
            </form>
        </div>
    </section>
</div>
{% endblock %}

templates/polls/poll_list.html
{% extends 'base.html' %}
{% block content %}
<div id="container my-3">
    <section>
        <h4 class="border-bottom py-2">설문목록</h4>
        <div class="row">
            {% if question_list %}
                {% for question in question_list %}
                <div class="col-4 my-3">
                    <div class="card">
                        <div class="card-body">
                            <div class="card-text" style="line-height:2rem">
                                {{ question.question_text }}
                            </div>
                            <a href="{% url 'poll:detail' question.id %}" class="btn btn-primary mt-5"> 투표하기 &raquo;</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            {% else %}
                <p>설문이 없습니다.</p>
            {% endif %}
        </div>
    </section>
</div>
{% endblock %}

templates/polls/vote_result.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <section>
        <div class="jumbotron">
            <div class="text-center">
                <h1 >투표결과</h1>
            </div>
        </div>
        <h4 style="margin: 20px 280px;">{{ question.question_text }}</h4>
        <ul style="width:500px; margin:0 auto";>
        {% for choice in question.choice_set.all %}
        <li style="margin: 20px;">
            <p style="font-size:1.2rem;">{{ choice.choice_text }} -- {{ choice.votes }}votes</p>
        </li>
        {% endfor %}
        </ul>
    </section>
</div>
{% endblock %}