board/urls.py
from django.urls import path
from board.views import base_views, question_views, answer_views, vote_views, comment_views

app_name = 'board'  #네임 스페이스 설정

urlpatterns = [
    #127.0.0.1:8000/board/
    #메인페이지
    path('', base_views.index, name='index'),
    #질문목록
    path('boardlist/', base_views.boardlist, name='boardlist'),
    #질문/답변 상세
    path('<int:question_id>/', base_views.detail, name='detail'),
    #질문 등록
    path('question/create/', question_views.question_create, name='question_create'),
    #질문 수정일
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    #질문 삭제
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),
    #답변 등록
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    #답변 수정일
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    #답변 삭제
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),
    #질문 추천
    path('vote/question/<int:question_id>/', vote_views.vote_question, name='vote_question'),
    #질문 댓글 등록
    path('comment/create/question/<int:question_id>/', comment_views.comment_create_question, name='comment_create_question'),
    #질문 댓글 삭제
    path('comment/delete/question/<int:comment_id>/', comment_views.comment_delete_question, name='comment_delete_question'),
    #질문 댓글 수정
    path('comment/modify/question/<int:comment_id>/', comment_views.comment_modify_question, name='comment_modify_question'),
]

common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from common import views

app_name = 'common'  #네임 스페이스 설정

urlpatterns = [
    #LoginView 클래스(제네릭 뷰)를 사용하면 제어함수를 만들지 않음
    #로그인
    path('login/', auth_views.LoginView.as_view(
        template_name='common/login.html'), name='login'),
    #로그아웃
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    #회원 가입
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from board.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', base_views.index),   #127.0.0.1:8000
    path('board/', include('board.urls')),
    path('common/', include('common.urls')),
    path('polls/', include('polls.urls')),
]

common/models.py
from django.db import models

# Create your models here.

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm): #부모 필드(username, password1, password2)
    email = forms.EmailField() #추가 필드

    class Meta:
        model = User
        fields = ('username', 'email')  #튜플 구조임

common/views.py
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect

from common.forms import UserForm

def signup(request):
    #회원 가입
    if request.method == "POST":
        form = UserForm(request.POST) #입력값을 가져옴
        if form.is_valid():
            form.save()  #실제 저장
            #가입후 자동 로그인
            username = form.cleaned_data.get('username')  #전달받은 사용자ID 가져옴
            password = form.cleaned_data.get('password1') #전달받은 비밀번호를 가져옴
            user = authenticate(username=username, password=password)  #세션(인증) 발급
            login(request, user)                     #로그인
            return redirect('board:index')
    else:
        form = UserForm() #비어있는 새폼
    return render(request, 'common/signup.html', {'form':form})

templates/common/login.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <section>
    <div class="row my-3">
        <div class="col-4">
            <h4>로그인</h4>
        </div>
        <div class="col-8 text-right">
            <span>또는 <a href="{% url 'common:signup' %}">계정을 만드세요</a></span>
        </div>
    </div> <!--row 끝-->
    <form action="" method="post" class="my-3">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">
        {% include 'form_errors.html' %}
        <div class="form-group">
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" id="username" name="username"
                   value="{{ form.username.value|default_if_none:'' }}">
            <!-- name 속성값은 반드시 username로 할 것-->
        </div>
        <div class="form-group">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" id="password" name="password"
                   value="{{ form.password.value|default_if_none:'' }}">
            <!-- name 속성값은 반드시 username로 할 것-->
        </div>
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>
    </section>
</div>
{% endblock %}

templates/common/signup.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <section>
    <div class="row my-3">
        <div class="col-4">
            <h4>회원가입</h4>
        </div>
        <div class="col-8 text-right">
            <span>또는 <a href="{% url 'common:login' %}">로그인 하세요</a></span>
        </div>
    </div>
    <form action="{% url 'common:signup' %}" method="post" class="my-3">
        {% csrf_token %}
        {% include 'form_errors.html' %}
        <div class="form-group">
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" id="username" name="username"
                   value="{{ form.username.value|default_if_none:'' }}">
            <!-- name 속성값은 반드시 username로 할 것-->
        </div>
        <div class="form-group">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" id="password1" name="password1"
                   value="{{ form.password1.value|default_if_none:'' }}">
            <!-- name 속성값은 반드시 username로 할 것-->
        </div>
        <div class="form-group">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" id="password2" name="password2"
                   value="{{ form.password2.value|default_if_none:'' }}">
            <!-- name 속성값은 반드시 username로 할 것-->
        </div>
        <div class="form-group">
            <label for="email">이메일</label>
            <input type="text" class="form-control" id="email" name="email"
                   value="{{ form.email.value|default_if_none:'' }}">
            <!-- name 속성값은 반드시 username로 할 것-->
        </div>
        <button type="submit" class="btn btn-primary">가입하기</button>
    </form>
    </section>
</div>
{% endblock %}