board/urls.py
from django.urls import path
from board.views import base_views, question_views, answer_views, vote_views, comment_views

app_name = 'board'  #네임 스페이스 설정

urlpatterns = [
    #127.0.0.1:8000/board/
    #메인페이지
    path('', base_views.index, name='index'),
    #질문목록
    path('boardlist/', base_views.boardlist, name='boardlist'),
    #질문/답변 상세
    path('<int:question_id>/', base_views.detail, name='detail'),
    #질문 등록
    path('question/create/', question_views.question_create, name='question_create'),
    #질문 수정일
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    #질문 삭제
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),
    #답변 등록
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    #답변 수정일
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    #답변 삭제
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),
    #질문 추천
    path('vote/question/<int:question_id>/', vote_views.vote_question, name='vote_question'),
    #질문 댓글 등록
    path('comment/create/question/<int:question_id>/', comment_views.comment_create_question, name='comment_create_question'),
    #질문 댓글 삭제
    path('comment/delete/question/<int:comment_id>/', comment_views.comment_delete_question, name='comment_delete_question'),
    #질문 댓글 수정
    path('comment/modify/question/<int:comment_id>/', comment_views.comment_modify_question, name='comment_modify_question'),
]

common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from common import views

app_name = 'common'  #네임 스페이스 설정

urlpatterns = [
    #LoginView 클래스(제네릭 뷰)를 사용하면 제어함수를 만들지 않음
    #로그인
    path('login/', auth_views.LoginView.as_view(
        template_name='common/login.html'), name='login'),
    #로그아웃
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    #회원 가입
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from board.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', base_views.index),   #127.0.0.1:8000
    path('board/', include('board.urls')),
    path('common/', include('common.urls')),
    path('polls/', include('polls.urls')),
]

polls/urls.py
from django.urls import path
from polls import views
#네임 스페이스
app_name = 'poll'  #app_name변수에 poll앱 저장

urlpatterns = [
    path('', views.poll_list, name='index'), # 127.0.0.1:8000/poll/
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/vote/', views.vote, name='vote'),
]

board/views/base_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from board.models import Question, Answer, Comment
from board.forms import QuestionForm, AnswerForm, CommentForm

def index(request):
    return render(request, 'board/index.html')

def boardlist(request):

    page = request.GET.get('page', '1')
    kw = request.GET.get('kw', '')

    #조회
    question_list = Question.objects.order_by('-create_date')
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |
            Q(content__icontains=kw) |
            Q(author__username__icontains=kw) | #질문 글쓴이
            Q(answer__author__username__icontains=kw) |   #답변 글쓴이
            Q(answer__content__icontains=kw)
        ).distinct() #유일한 것 검색

    #페이징 처리
    paginator = Paginator(question_list, 10)
    page_obj = paginator.get_page(page)
    context = {'question_list':page_obj, 'page':page, 'kw':kw}
    return render(request, 'board/question_list.html',context)


def detail(request, question_id):
    # 질문/답변 상세
    # question = Question.objects.get(id=question_id) #해당 id의 질문
    question = get_object_or_404(Question, pk=question_id)
    #경로에 오류가 있을 때 404로 처리(페이지가 없음)
    return render(request, 'board/detail.html', {'question':question})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hi~ pyweb</title>
    <link rel="stylesheet" href="{% static 'board/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'board/css/style.css' %}">
</head>
<body>
    {% include 'navbar.html' %}
    <!-- 기본 템플릿 안에 삽입될 내용 start -->
    {% block content %}
    <!-- content -->
    {% endblock %}
    <!-- 기본 템플릿 안에 삽입될 내용 end -->
    {% include 'footer.html' %}
    <!-- footer 추가 -->
    <script src="{% static 'board/js/jquery-3.6.0.js' %}"></script>
    <script src="{% static 'board/js/bootstrap.js' %}"></script>
    {% block script %}
    <!-- script -->
    {% endblock %}
</body>
</html>

templates/footer.html
<footer class="p-2 bg-dark">
    <div class="container">
    <ul class="list-inline">
        <li><a href="#">회사소개</a></li>
        <li><a href="#">개인정보 처리방침</a></li>
        <li><a href="#">여행약관</a></li>
        <li><a href="#">사이트 맵</a></li>
    </ul>
    <address>
        <p>대표이사 : 파이썬 | 대표전화 : 032-262-0680 | E-MAIL : meta@bus.net</p>
        <p>주소 : 인천시 부평구 경원대로 1366 상록스테이션 5층</p>
        <p>사업자 등록 번호 : 000-00-00000</p>
    </address>
    </div>
</footer>

templates/form_errors.html
<!-- 오류 표시 -->
{% if form.errors %}
    {% for field in form %}<!--필드(항목)가 여러개 이므로 중첩for-->
        {% for error in field.errors %}
        <div class="alert alert-danger">
            <strong>{{ field.label }}</strong>
            {{ error }}
        </div>
        {% endfor %}
    {% endfor %}
{% endif %}

templates/navbar.html
<!-- 네비게이션 바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{% url 'board:index' %}">blog</a>
    <!--햄버거 메뉴 -->
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse"
            data-target="#navbarNav" aria-controls="navbarNav"
            aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
<!-- 로그인 메뉴 -->
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                {% if user.is_authenticated %} <!-- 로그인(세션권한 인증) 되었다면 -->
                    <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }}(로그아웃)</a>
                {% else %}
                    <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                {% endif %}
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'board:boardlist' %}">질문/답변</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'poll:index' %}">설문조사</a>
            </li>
        </ul>
    </div>
</nav>