board/urls.py
from django.urls import path
from board.views import base_views, question_views, answer_views, vote_views, comment_views

app_name = 'board'  #네임 스페이스 설정

urlpatterns = [
    #127.0.0.1:8000/board/
    #메인페이지
    path('', base_views.index, name='index'),
    #질문목록
    path('boardlist/', base_views.boardlist, name='boardlist'),
    #질문/답변 상세
    path('<int:question_id>/', base_views.detail, name='detail'),
    #질문 등록
    path('question/create/', question_views.question_create, name='question_create'),
    #질문 수정일
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    #질문 삭제
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),
    #답변 등록
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    #답변 수정일
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    #답변 삭제
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),
    #질문 추천
    path('vote/question/<int:question_id>/', vote_views.vote_question, name='vote_question'),
    #질문 댓글 등록
    path('comment/create/question/<int:question_id>/', comment_views.comment_create_question, name='comment_create_question'),
    #질문 댓글 삭제
    path('comment/delete/question/<int:comment_id>/', comment_views.comment_delete_question, name='comment_delete_question'),
    #질문 댓글 수정
    path('comment/modify/question/<int:comment_id>/', comment_views.comment_modify_question, name='comment_modify_question'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from board.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', base_views.index),   #127.0.0.1:8000
    path('board/', include('board.urls')),
    path('common/', include('common.urls')),
    path('polls/', include('polls.urls')),
]

board/models.py
from django.contrib.auth.models import User
from django.db import models

class Question(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_question')
    subject = models.CharField(max_length=100)  #제목 칼럼
    content = models.TextField()                #질문 내용
    create_date = models.DateTimeField()        #질문 작성일
    modify_date = models.DateTimeField(null=True, blank=True)   #질문 수정일
    voter = models.ManyToManyField(User, related_name='voter_question')     #추천수(多(사람):多(글))
    # 일:다 - ForeignKey
    # 추천수 - 다:다 - ManyToManyField

    def __str__(self):
        return self.subject

class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE) #외래키, 제목
    content = models.TextField()          #답변 내용
    create_date = models.DateTimeField()  #답변 작성일
    modify_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.content


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()    #작성일
    modify_date = models.DateTimeField(null=True, blank=True)
    question = models.ForeignKey(Question, null=True, blank=True, on_delete=models.CASCADE)     #질문 댓글
    answer = models.ForeignKey(Answer, null=True, blank=True, on_delete=models.CASCADE)     #답변 댓글

board/forms.py
from django import forms
from board.models import Question, Answer, Comment

#질문 등록폼
class QuestionForm(forms.ModelForm):
    class Meta:     #내부클래스, 중첩클래스
        model = Question
        fields = ['subject', 'content']
        labels = {
            'subject':'제목',
            'content':'내용'
        }

# 답변 등록폼
class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {'content':'내용'}

# 댓글 등록폼
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        labels = {'content':'댓글 내용'}

board/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from board.models import Question, Answer, Comment
from board.forms import QuestionForm, AnswerForm, CommentForm

def index(request):
    return render(request, 'board/index.html')

def boardlist(request):

    page = request.GET.get('page', '1')
    kw = request.GET.get('kw', '')

    #조회
    question_list = Question.objects.order_by('-create_date')
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |
            Q(content__icontains=kw) |
            Q(author__username__icontains=kw) | #질문 글쓴이
            Q(answer__author__username__icontains=kw) |   #답변 글쓴이
            Q(answer__content__icontains=kw)
        ).distinct() #유일한 것 검색

    #페이징 처리
    paginator = Paginator(question_list, 10)
    page_obj = paginator.get_page(page)
    context = {'question_list':page_obj, 'page':page, 'kw':kw}
    return render(request, 'board/question_list.html',context)


def detail(request, question_id):
    # 질문/답변 상세
    # question = Question.objects.get(id=question_id) #해당 id의 질문
    question = get_object_or_404(Question, pk=question_id)
    #경로에 오류가 있을 때 404로 처리(페이지가 없음)
    return render(request, 'board/detail.html', {'question':question})

@login_required(login_url='common:login')
def question_create(request):
    #질문 등록
    if request.method == "POST":
        form = QuestionForm(request.POST)   #자료 전달받음(request.POST)
        if form.is_valid():
            question = form.save(commit=False) #가저장(날짜가 없어서 가저장)
            question.author = request.user
            question.create_date = timezone.now() #날짜 시간 저장
            question.save()  #실제 저장
            return redirect('board:index') #이동할 경로(앱 네임사용) 저장
    else:
        form = QuestionForm()   #form 객체 생성
    return render(request, 'board/question_form.html', {'form':form})

@login_required(login_url='common:login')
def answer_create(request, question_id):
    #답변 등록
    #question = Question.objects.get(id=question_id) #해당 id의 질문 객체 생성
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST) #입력값 전달받음
        if form.is_valid():
            answer = form.save(commit=False)  #내용만 저장됨
            answer.author = request.user
            answer.create_date = timezone.now() #작성일
            answer.question = question  #외래키 질문 저장
            answer.save()
            return redirect('board:detail', question_id=question.id)
    else:
        form = AnswerForm()
    context = {'question':question,'form':form}
    return render(request, 'board/detail.html', context)

#질문 수정
@login_required(login_url='common:login')
def question_modify(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '수정권한이 없습니다.')
        return redirect('board:detail', question_id=question.id)

    if request.method =="POST":
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.modify_date = timezone.now()
            question.save()
            return redirect('board:detail', question_id=question.id)
    else:
        form = QuestionForm(instance=question)
    context = {'form':form}
    return render(request, 'board/question_form.html', context)

#질문 삭제
@login_required(login_url='common:login')
def question_delete(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '삭제권한이 없습니다.')
        return redirect('board:detail', question_id=question.id)
    question.delete()
    return redirect('board:index')

#답변수정
@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.method =="POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.modify_date = timezone.now()
            answer.save()
            return redirect('board:detail', question_id=answer.question.id)
    else:
        form = AnswerForm(instance=answer)
    context = {'answer':answer, 'form':form}
    return render(request, 'board/answer_form.html', context)

#답변 삭제
@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    answer.delete()
    return redirect('board:detail', question_id=answer.question.id)

#질문 추천
@login_required(login_url='common:login')
def vote_question(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user == question.author:
        messages.error(request, '본인이 작성한 글은 추천할 수 없습니다.')
    else:
        question.voter.add(request.user)    #추천 추가(로그인한 사람)
    return redirect('board:detail', question_id=question.id)

#질문 답변
@login_required(login_url='common:login')
def comment_create_question(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user   #세션 권한
            comment.create_date = timezone.now()
            comment.question = question     #참조권한
            comment.save()
            return redirect('board:detail', question_id=question.id)
    else:
        form = CommentForm()
    context = {'form':form}
    return render(request, 'board/comment_form.html', context)

#질문 댓글 삭제
@login_required(login_url='common:login')
def comment_delete_question(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    comment.delete()
    return redirect('board:detail', question_id=comment.question.id)\

#질문 댓글 수정
@login_required(login_url='common:login')
def comment_modify_question(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)  #변경된 입력 내용
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.modify_date = timezone.now()
            comment.save()
            return redirect('board:detail', question_id=comment.question.id)
    else:
        form = CommentForm(instance=comment)    #채워진 폼
    context = {'form':form}
    return render(request, 'board/comment_form.html', context)

board/views/answer_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from board.models import Question, Answer, Comment
from board.forms import QuestionForm, AnswerForm, CommentForm

@login_required(login_url='common:login')
def answer_create(request, question_id):
    #답변 등록
    #question = Question.objects.get(id=question_id) #해당 id의 질문 객체 생성
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST) #입력값 전달받음
        if form.is_valid():
            answer = form.save(commit=False)  #내용만 저장됨
            answer.author = request.user
            answer.create_date = timezone.now() #작성일
            answer.question = question  #외래키 질문 저장
            answer.save()
            return redirect('board:detail', question_id=question.id)
    else:
        form = AnswerForm()
    context = {'question':question,'form':form}
    return render(request, 'board/detail.html', context)

#답변수정
@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.method =="POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.modify_date = timezone.now()
            answer.save()
            return redirect('board:detail', question_id=answer.question.id)
    else:
        form = AnswerForm(instance=answer)
    context = {'answer':answer, 'form':form}
    return render(request, 'board/answer_form.html', context)

#답변 삭제
@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    answer.delete()
    return redirect('board:detail', question_id=answer.question.id)

board/views/base_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from board.models import Question, Answer, Comment
from board.forms import QuestionForm, AnswerForm, CommentForm

def index(request):
    return render(request, 'board/index.html')

def boardlist(request):

    page = request.GET.get('page', '1')
    kw = request.GET.get('kw', '')

    #조회
    question_list = Question.objects.order_by('-create_date')
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |
            Q(content__icontains=kw) |
            Q(author__username__icontains=kw) | #질문 글쓴이
            Q(answer__author__username__icontains=kw) |   #답변 글쓴이
            Q(answer__content__icontains=kw)
        ).distinct() #유일한 것 검색

    #페이징 처리
    paginator = Paginator(question_list, 10)
    page_obj = paginator.get_page(page)
    context = {'question_list':page_obj, 'page':page, 'kw':kw}
    return render(request, 'board/question_list.html',context)


def detail(request, question_id):
    # 질문/답변 상세
    # question = Question.objects.get(id=question_id) #해당 id의 질문
    question = get_object_or_404(Question, pk=question_id)
    #경로에 오류가 있을 때 404로 처리(페이지가 없음)
    return render(request, 'board/detail.html', {'question':question})

board/views/comment_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from board.models import Question, Answer, Comment
from board.forms import QuestionForm, AnswerForm, CommentForm

#질문 답변
@login_required(login_url='common:login')
def comment_create_question(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user   #세션 권한
            comment.create_date = timezone.now()
            comment.question = question     #참조권한
            comment.save()
            return redirect('board:detail', question_id=question.id)
    else:
        form = CommentForm()
    context = {'form':form}
    return render(request, 'board/comment_form.html', context)

#질문 댓글 삭제
@login_required(login_url='common:login')
def comment_delete_question(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    comment.delete()
    return redirect('board:detail', question_id=comment.question.id)\

#질문 댓글 수정
@login_required(login_url='common:login')
def comment_modify_question(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)  #변경된 입력 내용
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.modify_date = timezone.now()
            comment.save()
            return redirect('board:detail', question_id=comment.question.id)
    else:
        form = CommentForm(instance=comment)    #채워진 폼
    context = {'form':form}
    return render(request, 'board/comment_form.html', context)

board/views/vote_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from board.models import Question, Answer, Comment
from board.forms import QuestionForm, AnswerForm, CommentForm

#질문 추천
@login_required(login_url='common:login')
def vote_question(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user == question.author:
        messages.error(request, '본인이 작성한 글은 추천할 수 없습니다.')
    else:
        question.voter.add(request.user)    #추천 추가(로그인한 사람)
    return redirect('board:detail', question_id=question.id)

templates/board/answer_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <section>
    <form method="post" class="post-form">
        {% csrf_token %}
        <!-- 오류 표시 시작-->
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="content">답변내용</label>
            <textarea name="content" id="content" rows="10" class="form-control">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <input type="submit" value="저장하기" class="btn btn-primary">
    </form>
    </section>
</div>
{% endblock %}

templates/board/comment_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
<section>
    <h5 class="border-bottom my-3 pb-2">댓글 등록</h5>
    <form action="" method="post">
        {% csrf_token %}
        {% include 'form_errors.html' %}
        <div class="form-group">
            <label for="content">댓글 내용 : </label>
            <textarea name="content" id="content"
                      rows="5" cols="40" class="form-control">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <input type="submit" value="저장하기" class="btn btn-primary">
    </form>
</section>
</div>
{% endblock %}

templates/board/detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <!-- 추천 오류 -->
    {% if messages %}
        <div class="alert alert-danger my-3" role="alert">
        {% for message in messages %}
            <strong>{{ message.tags }}</strong>
            <ul>
                <li>{{ message.massage }}</li>
            </ul>
        {% endfor %}
        </div>
    {% endif %}
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <!-- 추천 영역 -->
    <div class="row">
        <div class="col-1">
            <div class="bg-light text-center border font-weight-bolder p-3">
                {{ question.voter.count }}
            </div>
            <a href="#" data-uri="{% url 'board:vote_question' question.id %}"
               class="recommend btn btn-sm btn-secondary btn-block my-1">추천</a>
        </div>
        <div class="col-11">
        <!-- 질문 영역 -->
            <div class="card my-3">
                <div class="card-body">
                    <div class="card-text" style="white-space:pre-line"> <!--style은 줄바꿈 출력-->
                        {{ question.content }}
                    </div>
                    <div class="d-flex justify-content-end"><!--오른쪽 정렬-->
                        {% if question.modify_date %}
                        <div class="badge badge-light text-left p-2">
                            <div class="mb-2">modefied at</div>
                            <div>{{ question.modify_date }}</div>
                        </div>
                        {% endif %}
                        <div class="badge badge-light text-left p-2">
                            <div class="mb-2">{{ question.author }}</div>
                            <div>{{ question.create_date }}</div>
                        </div>
                    </div>
                    {% if request.user == question.author %}
                    <div>
                        <a href="{% url 'board:question_modify' question.id %}"
                           class="btn btn-sm btn-outline-secondary">수정</a>
                        <a href="#" data-uri="{% url 'board:question_delete' question.id %}"
                           class="delete btn btn-sm btn-outline-secondary">삭제</a>
                    </div>
                    {% endif %}
                    <!-- 댓글 영역 -->
                    <div class="mt-3">
                        {% for comment in question.comment_set.all %}
                        <div class="comment my-2 text-muted">
                            <span style="white-space:pre-line">
                                {{ comment.content }}
                            </span>
                            <span>
                                -{{ comment.author }}, {{ comment.create_date }}
                                {% if comment.modify_date %}
                                    (수정 : {{ comment.modify_date }})
                                {% endif %}
                            </span>
                            {% if request.user == comment.author %}
                            <!-- 제이쿼리 사용 -->
                            <a href="{% url 'board:comment_modify_question' comment.id %}">수정</a>
                             <a href="#" class="delete" data-uri="{% url 'board:comment_delete_question' comment.id %}">삭제</a>
                            <!-- 자바스크립트 사용-->
<!--                            <a onclick="return confirm('정말로 삭제하시겠습니까?')"-->
<!--                               href="{% url 'board:comment_delete_question' comment.id %}">삭제</a>-->
                            {% endif %}
                        </div>
                        {% endfor %}
                    </div>
                    <div>
                        <a href="{% url 'board:comment_create_question' question.id %}" class="small">댓글추가</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <h5 class="border-bottom my-3 py-2">
        {{ question.answer_set.count }}개의 답변이 있습니다.
    </h5>
    {% for answer in question.answer_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space:pre-line">
                {{ answer.content }}
            </div>
            <div class="d-flex justify-content-end"><!--오른쪽 정렬-->
                {% if answer.modify_date %}
                <div class="badge badge-light text-left p-2">
                    <div class="mb-2">modefied at</div>
                    <div>{{ answer.modify_date }}</div>
                </div>
                {% endif %}
                <div class="badge badge-light text-left p-2">
                    <div class="mb-2">{{ answer.author }}</div>
                    <div>{{ answer.create_date }}</div>
                </div>
            </div>
            {% if request.user == answer.author %}
            <div>
                <a href="{% url 'board:answer_modify' answer.id %}"
                   class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="#" data-uri="{% url 'board:answer_delete' answer.id %}"
                   class="delete btn btn-sm btn-outline-secondary">삭제</a>
            </div>
            {% endif %}
        </div>
    </div>
    {% endfor %}
    <form action="{% url 'board:answer_create' question.id %}" method="post">
        {% csrf_token %}
        <!-- 오류 표시 시작 -->
            {% if form.errors %}
            <div class="alert alert-danger">
                {% for field in form %}
                    {% if field.errors %}
                        <strong>{{ field.label }}</strong>
                        {{ field.errors }}
                    {% endif %}
                {% endfor %}
            </div>
            {% endif %}
        <!-- 오류 표시 끝-->
        <div class="form-group">
            <textarea name="content" rows="7" cols="50" class="form-control"
                        {% if not user.is_authenticated %}
                            disabled
                        {% endif %}></textarea>
        </div>
        <input type="submit" value="답변 등록" class="btn btn-primary">
    </form>
</div>
{% endblock %}
{% block script %}
<script>
    $(document).ready(function(){
        //삭제처리
        $(".delete").on('click', function(){
            if(confirm('정말로 삭제하시겠습니까?')){
                location.href = $(this).data('uri');
            }
        });
        //추천 처리
        $(".recommend").on('click', function(){
            if(confirm("정말로 추천하시겠습니까?")){
                location.href = $(this).data('uri');
            }
        });
    });

</script>
{% endblock %}

templates/board/index.html
{% extends 'base.html' %}
{% block content %}
<section>
<div class="jumbotron">
    <div class="text-center">
            <h1>Welcome~ Have a nice day!</h1>
    </div>
</div>
<div class="text-center">
    <img src="../../static/board/images/coffee-gray.jpg">
    <p id="demo"></p>
</div>
</section>
<script src="../../static/board/js/main_js.js"></script>
{% endblock%}

templates/board/question_list.html
{% extends 'base.html' %}
{% load board_filter %}
{% block content %}
<div class="container my-3">
    <section>
        <!-- 검색 입력 상자와 찾기 버튼-->
        <div class="row justify-content-end mb-2">
            <div class="col-4 input-group">
                <input type="text" class="kw form-control" value="{{ kw|default_if_none:'' }}">
                <div class="input-group-append">
                    <button type="button" id="btn_search" class="btn btn-outline-secondary">찾기</button>
                </div>
            </div>
        </div>

        <!-- 게시판 목록 -->
        <table class="table">
            <thead class="thead-dark">
                <tr class="text-center thead-dark">
                    <th>번호</th><th>추천</th><th>제목</th><th>글쓴이</th><th>작성일시</th>
                </tr>
            </thead>
            <tbody>
                {% if question_list %}
                    {% for question in question_list  %}
                    <tr class="text-center">
                        <!-- <td>{{ forloop.counter }}</td>-->
                        <td>{{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1}}</td>
                        <td>
                            {% if question.voter.all.count > 0 %}
                            <span class="badge badge-warning px-2 py-1">
                                {{ question.voter.all.count }}
                            </span>
                            {% endif %}
                        </td>
                        <td class="text-left">
                            <!--링크 경로는 앱 네임을 사용함-->
                            <a href="{% url 'board:detail' question.id %}">
                                {{ question.subject }}
                            </a>
                            {% if question.answer_set.count > 0 %}
                            <span class="text-danger small">[{{ question.answer_set.count }}]</span>
                            {% endif %}
                        </td>
                        <td>{{ question.author.username }}</td>
                        <td>{{ question.create_date }}</td>
                    </tr>
                    {% endfor %}
                {% else %}
                <p>질문이 없습니다.</p>
                {% endif %}
            </tbody>
        </table>
        <!-- 페이징 처리 시작 -->
        <ul class="pagination justify-content-center">
            <!-- 이전 페이지-->
            {% if question_list.has_previous %}
            <li class="page-item">
<!--                <a class="page-link"  href="?page={{ question_list.previous_page_number }}">이전</a>-->
                <a class="page-link"  data-page="{{ question_list.previous_page_number }}">이전</a>
            </li>
            {% else %}
            <li class="page-item disable">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
            </li>
            {% endif %}
            <!-- 페이지 리스트 -->
            {% for page_number in question_list.paginator.page_range %}
                {% if page_number == question_list.number %}
                <li class="page-item active" aria-current="page">   <!--번호활성화-->
<!--                <a class="page-link"-->
<!--                    href="?page={{ page_number }}">{{ page_number }}</a>-->
                    <a class="page-link" href="#"
                        data-page="{{ page_number }}">{{ page_number }}</a>
                </li>
                {% else %}
                <li class="page-item">
<!--                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>-->
                    <a class="page-link" href="#"
                        data-page="{{ page_number }}">{{ page_number }}</a>
                </li>
                {% endif %}
            {% endfor %}
            <!-- 다음 페이지-->
            {% if question_list.has_next %}
            <li class="page-item">
<!--                <a class="page-link"  href="?page={{ question_list.next_page_number }}">다음</a>-->
                <a class="page-link"  data-page="{{ question_list.next_page_number }}">다음</a>
            </li>
            {% else %}
            <li class="page-item disable">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
            </li>
            {% endif %}
        </ul>
        <!-- 페이징 처리 끝 -->
        <a class="btn btn-primary"
           href="{% url 'board:question_create' %}">질문 등록</a>
        <!-- 검색 폼 만들기 -->
        <form action="" method="get" id="searchForm">
            <!-- page, kw는 get방식으로 요청-->
            <input type="hidden" name="kw" id="kw">
            <input type="hidden" name="page" id="page">
        </form>
    </section>
</div>
{% endblock %}
{% block script%}
<script>
    $(document).ready(function(){
        //페이지 처리
        $(".page-link").on('click',function(){      //페이지 번호를 클릭하면
            $("#page").val($(this).data("page"));   //해당 페이지 번호를 입력 필드에 가져옴
            $("#searchForm").submit();              //폼을 전송
        });

        //검색 처리
        $("#btn_search").on('click', function(){
            let text = $(".kw").val()               //검색어 값
            $("#kw").val(text);                     //폼에 입력 필드에 설정
            $("#page").val(1);                      //1페이지를 page 필드에 설정
            $("#searchForm").submit();              //폼을 전송
            });

    });
</script>
{% endblock %}